[package]
name = "meno"
version = "0.1.0"
edition = "2021"
description = "A fundamental physics simulator"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
rand = "0.8.5"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
wgpu = "0.15.1"
winit = "0.28.3"
tokio = { version = "1", features = ["full"] }
